name: Build and Deploy
on:
  push:
    branches:
    - staging
    - production
    - devenv
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
#     - name: Build Hugo
#       uses: lowply/build-hugo@v0.68.3
    - name: nodejs setup
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.5
      env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        FIREBASE_PROJECT: "fir-785b7"
        TARGET_NAME: ${GITHUB_REF#refs/heads/}
